export default function HowItWorks() {
  return (
    <section style={{ maxWidth: 700, margin: "0 auto" }}>
      <h2 style={{ fontSize: "1.8rem", textAlign: "center", marginBottom: "1rem" }}>
        How it works
      </h2>

      <ol
        style={{
          listStyle: "decimal",
          paddingLeft: "1.2rem",
          display: "grid",
          gap: "0.75rem",
          fontSize: "1rem",
          color: "#444",
        }}
      >
        <li><strong>Upload an image</strong> of notes or a textbook page.</li>
        <li><strong>Or type a topic</strong> you want to learn.</li>
        <li><strong>Get an instant quiz</strong> generated by AI.</li>
      </ol>
    </section>
  );
}
